pluginpal/strapi-webtools

server/content-api/routes/path.js
=> fix: Auth of routes

admin/components/EditView/index.tsx
After #32 the editview box was just constantly loading
Now it will actually load without failing
#32
=> fix(EditView): Loading state is now correct

server/admin-api/services/lifecycle.ts, server/index.ts
Since we do not know what the params of the event is, we can use those events in a query and fetch the correct entries. We can then delete the correct url paths
fixes #26
Deleting a locale should now work
#26
=> fix(lifecycles): BeforeDeleteMany lifecycle will correctly fetch results

.eslintignore, package.json, server/admin-api/controllers/pattern.ts, server/admin-api/services/lifecycle.ts, server/admin-api/services/path.ts, server/admin-api/services/pattern.ts, server/content-api/services/by-path.ts, server/util/getPluginService.ts, tsconfig.server.json, types/generated.d.ts, yarn.lock
Fixes types for plugin internal services
More type safety
=> feat: Added types to servies through getPluginService()

.changeset/mighty-spoons-stare.md, MIGRATION.md, migrations/2023.06.12T00.00.00.url-alias-to-webtools.js, package.json, packages/addons/menus/admin/src/components/EditView/index.tsx, packages/addons/menus/admin/src/index.tsx, packages/addons/menus/package.json, packages/addons/redirects/admin/src/components/EditView/index.tsx, packages/addons/redirects/admin/src/index.tsx, packages/addons/redirects/package.json, packages/addons/sitemap/admin/src/components/EditView/index.tsx, packages/addons/sitemap/admin/src/index.tsx, packages/addons/sitemap/package.json, packages/core/admin/components/EditView/index.tsx, packages/core/admin/index.ts, packages/core/package.json, packages/helper-plugin/package.json, yarn.lock
=> refactor: rename @strapi-webtools to @pluginpal/webtools

packages/core/admin/screens/Patterns/CreatePage/index.tsx, packages/core/admin/screens/Patterns/EditPage/index.tsx, yarn.lock
=> chore: security updates

.changeset/old-worms-hear.md, packages/core/server/admin-api/services/query-layer-decorator.ts, packages/core/server/types/strapi.ts
Fix an issue in the query layer decorator
To solve #105 
Test if #105 is solved
=> fix: bug in query-layer-decorator

.changeset/dry-jobs-joke.md, packages/core/server/admin-api/__tests__/query-layer-decorator.test.ts, packages/core/server/admin-api/services/url-alias.ts, playground/config/env/test/database.ts, playground/package.json, playground/src/index.ts, playground/tests/helpers.js, playground/yarn.lock
The duplicateCheck function should ignore itself when checking duplicates.
Fixes bug from #115
=> fix: duplicateCheck will use an ignore id

MIGRATION.md, migrations/2023.06.12T00.00.00.url-alias-to-webtools.js
Renames `path` column if it exists to `url_path`. It was named `path` prior to commit b14eb26f76b53a3a9ad91f050b04266224fc244d.
Also adds a note about singular name needs to be snake case
closes #92
=> Migration notes regarding singular name and rename path column

.changeset/clever-planes-serve.md, packages/core/server/admin-api/services/query-layer-decorator.ts, packages/core/server/admin-api/services/url-pattern.ts
Allows the user to add relational fields to their URL patterns
1. Pull this PR branch
2. Install all dependencies
3. Start the development env
4. Create a pattern with a relation field in it
5. Try to generate an URL alias by creating an entity.
#25
=> feat: relational patterns

packages/addons/sitemap/admin/index.ts, packages/addons/sitemap/admin/state/actions/Sitemap.js, packages/core/admin/api/url-alias.ts, packages/core/admin/screens/Patterns/EditPage/index.tsx, playground/types/generated/contentTypes.d.ts
Fix issues with data fetching introduced in #146 
@TMSchipper just tagging you here FYI
=> fix: issues with data fetching

.github/workflows/deploy-test-server.yml
=> fix: update branch name

.github/workflows/deploy-test-server.yml
=> fix: test deployment

.github/workflows/deploy-test-server.yml
=> fix: test deployemtn

playground/Dockerfile
=> fix: test server deploymentg

.github/workflows/deploy-test-server.yml
=> fix: deployments

playground/Dockerfile, playground/config/plugins.ts
=> chore: enable the webtools plugins in the playground

playground/config/plugins.ts
=> chore: temporarily disable webtools in playground

playground/Dockerfile
=> chore: fix test deploy

playground/Dockerfile
=> fix: properly copy the yalc folder

.github/workflows/deploy-test-server.yml, playground/Dockerfile, playground/config/plugins.ts
=> chore: clean up the dokku build after deployment

package.json, yarn.lock
=> fix: remove packages from the main package json

.github/workflows/deploy-docs.yml, .github/workflows/deploy-test-server.yml, .github/workflows/release.yml, .github/workflows/tests.yml, packages/docs/.github/workflows/deploy.yml
Update github actions to fix build issues.
See https://github.com/actions/setup-node/issues/1275#issuecomment-2808630427
=> fix: github workflows by updating actions

.changeset/wise-grapes-jump.md, packages/core/server/routes/index.ts
Expose the URL alias crud endpoints to the content-api.
To solve #329
=> URL alias crud endpoints
