pluginpal/strapi-webtools

- server/content-api/services/prepare-path.js
In case of broken relations in database (if we have url_path_id but missing corresponding record in url_paths table), we will get error:
```
[2022-11-09 09:51:26.651] error: Cannot read property 'url_path' of null
TypeError: Cannot read property 'url_path' of null
at /srv/app/node_modules/@strapi-community/strapi-plugin-url-alias/server/content-api/services/prepare-path.js:27:41
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async Promise.all (index 6)
at async Object.traverse [as preparePath] (/srv/app/node_modules/@strapi-community/strapi-plugin-url-alias/server/content-api/services/prepare-path.js:18:5)
at async Object.response (/srv/app/node_modules/@strapi-community/strapi-plugin-url-alias/server/content-api/services/prepare-path. …
```
> fix: Cannot read property 'url_path' of null

- admin/components/PatternField/index.tsx
The pattern field was using a popover, but after updating the design system package it fills the entire screen, making the field unusable. It will now be possible to dismiss the popover.
Try creating a new pattern and press outside the popover, the popover will now go away.
> fix(PatternField): Popover can now be dismissed

- server/admin-api/register.ts
It makes the `url_path_id`  field unique for the current content type and tells i18n that it should be localized (even though it is default).
The ids should be unique anyway, so this is just an extra protection to avoid wrong data on the different entries.
It helps prevent #33 but it still copies over the data, so we cannot close it
Follow the steps in #33 and see that you get an error instead
#33
> fix: `url_path_id` will now be unique

- admin/components/ContentManagerHooks/ConfirmationCheckbox/index.tsx
- admin/helpers/pluginId.ts
- admin/index.ts
- admin/types/app.ts
- package.json
- yarn.lock
Creates a checkbox to enable and disable url alias for all content types
Enabling url alias only for specific content types can improve performance and remove clutter. Especially for the end user editing content types that should not have a url.
TODO
resolves #15
> Enable url alias through sidebar

- admin/components/EditView/index.tsx
- admin/helpers/queries/info.ts
- admin/screens/Patterns/CreatePage/index.tsx
- admin/screens/Patterns/EditPage/index.tsx
- lib/schemas/getContentTypes.ts
- lib/schemas/pluginOptions.ts
- package.json
- server/admin-api/controllers/info.ts
- server/admin-api/controllers/pattern.ts
- server/admin-api/register.ts
- server/admin-api/routes/info.ts
- server/admin-api/services/info.ts
- server/admin-api/services/lifecycle.ts
- server/index.ts
- server/util/enabledContentTypes.ts
- strapi-admin.js
- strapi-server.js
- tsconfig.json
- tsconfig.server.json
- yarn.lock
If a content type has disabled url alias it will no longer show the url alias edit view in the content manager
Less clutter on the page, which gives a better user experience
Try disabling url alias for one of your content types and check in the content manager that it is longer there
#38
> feat(enable button): EditView is hidden if url alias is not enabled

- server/content-api/services/prepare-path.ts
After preparepath was modified it would no longer iterate over arrays, this pull request fixes that
Try finding many of an entity in the current version and in this version. In this PR it will populate the `url_path`.
> fix(preparePath): Will now check if the data is an array and iterate it

- server/admin-api/services/lifecycle.ts
It checks if the path entity actually exists. If it does not it will create a new one.
In certain cases the database may have wrong data since the `url_path_id` is not a relation.
Maybe related to #27 but I am not sure
> fix(lifecycles): create new path if id exists, but no entity

- playground/config/database.ts
The database path in playground needs to escape the dist folder so we need to add an extra ".."
I am not sure if you are experiencing the same.
I had an issue doing anything in the playground becuase the database folder would be created inside the dist folder.
> chore(playground): Fixed database path

- migrations/2023.06.12T00.00.00.url-alias-to-webtools.js
I was trying to migrate one of my live deployments in a staging environment and the migration script said it had run, but the table wasn't renamed and then the old tables were deleted.
I noticed that the code only runs the renaming if the table does not exist :thinking:, this should be fixed now.
Also, I couldn't get the script to work without awaiting the transactions.
I also added some console logs, so it may be easy to notice if anything goes wrong or something unexpected happens.
> fix(migration): should rename table if it exists and await transactions

- .changeset/dry-lions-wonder.md
- packages/core/server/admin-api/services/url-alias.ts
Prior to this commit, the duplicate check was run, but the new url path was not used.
This commit also refactors the duplicateCheck function to a separate function without side effects.
The duplicate check needs to run and use the new url path
> fix(urlAliasService): Use the duplicate checked url path

- .github/workflows/tests.yml
tests does not need to run if only non-js/ts files change, such as `.md` files
Saves compute time
For reference [Github actions docs for paths-ignore](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore)
> ci(tests): Does not need to run if only non-js/ts files change

- .changeset/cuddly-clouds-sneeze.md
- packages/core/admin/screens/Patterns/ListPage/index.tsx
Fix issue with not loading url patterns in bug report:  [issue-150](https://github.com/pluginpal/strapi-webtools/issues/150)
> feat: remove !pattern.length for loading state

- .changeset/olive-flowers-nail.md
- packages/addons/sitemap/server/services/core.js
- packages/addons/sitemap/server/utils/index.js
Backported this fix from the standalone sitemap plugin: https://github.com/pluginpal/strapi-plugin-sitemap/pull/178
Because the webtools sitemap addon will replace the standalone plugin.
> fix: check if a hostname is present before building the sitemap stream

- .changeset/hip-moons-beg.md
- packages/addons/sitemap/server/cli.js
> feat: fix cli commando for sitemap

- packages/core/server/config.ts
- packages/core/server/services/url-pattern.ts
Allow the slugify function to be set via config
Right now kebab deburr toLower is hardcoded as a sanitizer. One might want to sanitize themselves. (for example, allow slashes)
It should default to the original function in the config.
or set a different function in the config. This can be `@sindresorhus/slugify` or a custom function
closes https://github.com/pluginpal/strapi-webtools/issues/184
> allow to override the slugify function

- .changeset/eleven-papers-trade.md
- packages/core/admin/components/EditView/index.tsx
> Prevent unnecessary network requests

- .changeset/dark-items-bet.md
- packages/core/server/middlewares/generate-url-alias.ts
The status that is shown in the Strapi content manager had a bug.
Whilst using Webtools the status would never show "modified" even though the draft would have changes.
Reason for that being is that that "modified" status will be calculated by checking if the `updated_at` values of the draft & published versions are the same. Only if they are not the same, the status "modified" will be shown.
Now for Webtools; an update query will be ran for all entities of the document to link them to the url_alias. That will cause the `updated_at` value to increase. To prevent this the PR changes the `update` query to a `updateRelations` query. In this specific case they serve the same purpose, but the latter does not increase the `updated_at` value, preventing this issue.
Addresses #236
> Fix incorrect "modified" status

- CONTRIBUTING.md
Fix the egghead.io link in CONTRIBUTING.md.
> fix: contributing course link in CONTRIBUTING.md

- playground/config/env/test/database.ts
- playground/tests/helpers.ts
Improves developer experience by putting the temp db in playground/.tmp.
Adds typings to the test/helpers.ts file and adds/removes `await` where needed.
I was trying to figure out where the data was stored while running the tests. This change puts the data in a more visible location. While debugging the tests, I added some typescript typings to the helper file and discovered that some calls were awaited that did not return a promise and one async call was not awaited.
> fix: location of test db, awaiting strapi teardown

- .changeset/ten-times-shake.md
- packages/addons/sitemap/package.json
- packages/cli/package.json
- packages/core/package.json
- yarn.lock
Makes `yarn develop` in the root directory work (on my machine) by using the same commands in `webtools-addon-sitemap` as in the other packages.
To develop this plugin.
Run `yarn develop`.
Before:
```
PS C:\Projects\GitHub\strapi-webtools> yarn develop
turbo 2.5.0
WARNING  stale pid file at "C:\\Users\\Jorrit\\AppData\\Local\\Temp\\turbod\\ce4c85f987b81795\\turbod.pid"
• Packages in scope: docs, strapi-plugin-webtools, webtools-addon-sitemap, webtools-cli
• Running watch:link in 4 packages
• Remote caching disabled
strapi-plugin-webtools:watch:link: cache bypass, force executing 115673eb70ec7dc4
webtools-addon-sitemap:watch:link: cache bypass, force executing 9bcb1035dcb66c21
strapi-plugin-webtools:watch:link: [INFO] Watching ./dist for changes to files with extensions: …
```
> fix: simplify scripts by adding devDependencies

- .changeset/angry-points-bow.md
- .github/workflows/tests.yml
- packages/core/server/middlewares/__tests__/middlewares.test.js
- packages/core/server/middlewares/generate-url-alias.ts
> fix: response structure for cloned content to prevent issues

- .changeset/bumpy-sites-search.md
- packages/core/admin/components/EditForm/index.tsx
> fix: pass the locale to the URL alias update request to prevent issues

- .changeset/plain-states-reply.md
- jest.config.js
- packages/addons/sitemap/server/utils/enabledContentTypes.ts
- packages/core/server/config.ts
- packages/core/server/content-types/url-alias/schema.json
- packages/core/server/middlewares/__tests__/middlewares.test.js
- packages/core/server/middlewares/generate-url-alias.ts
- packages/core/server/middlewares/prevent-duplicate-urls.ts
- packages/core/server/services/url-alias.ts
- packages/core/server/util/enabledContentTypes.ts
- packages/docs/docs/configuration/unique-per-locale.md
- playground/src/index.ts
- playground/tests/healthcheck.test.js
- playground/tests/helpers.ts
- playground/types/generated/contentTypes.d.ts
Adds an option to generate unique urls per locale instead of across the entire site.
When the locale is already part of the URL (for instance, in the domain name or an externally provided path prefix) the URL does not need to be unique for the site, but just for the locale.
1. Create Strapi content with multiple locales but the same value for the fields in the placeholder(s).
2. Create URL patterns for these locales that are identical for the locales
3. Set the new config option `unique_per_locale` to true.
Addresses #289
> feat: unique aliases per locale

- .changeset/happy-zoos-relate.md
- packages/core/admin/containers/App/index.tsx
- packages/core/admin/screens/List/components/GeneratePathsModal/index.tsx
- packages/core/admin/screens/List/index.tsx
- packages/core/admin/screens/Overview/components/ContentTypesList/index.tsx
- packages/core/admin/screens/Overview/index.tsx
- packages/core/server/services/bulk-generate.ts
- packages/core/server/util/enabledContentTypes.ts
The primary goal was to show a spinner on the 'Bulk generate' button when generating. I also added some cosmetic changes in separate commits.
It's easy to accidently click twice on the Bulk generate button as it provides no feedback. When this process is started twice, the results are either no or duplicate aliases.
Start the playground, click the Bulk generate button. It should show a spinner.
> Show spinner when bulk generating aliases

- .changeset/better-symbols-smoke.md
- packages/core/admin/containers/App/index.tsx
- packages/core/admin/screens/List/index.tsx
- packages/core/admin/screens/Patterns/ListPage/index.tsx
- packages/core/admin/translations/en.json
- packages/core/admin/translations/nl.json
- packages/core/server/middlewares/__tests__/middlewares.test.js
- packages/core/server/middlewares/generate-url-alias.ts
- packages/core/server/services/bulk-generate.ts
- packages/core/server/services/url-alias.ts
- packages/core/server/services/url-pattern.ts
- turbo.json
My PR #291 causes a bug when updating / bulk generating documents that have no locale.
When updating a documents alias without a locale, a `-0` is always appended.
Create a content type without internationalization and create a document with that type. Then update it.
> Fixes for installations/content types without i18n

- .changeset/itchy-eggs-warn.md
- .changeset/twenty-wombats-burn.md
- packages/addons/sitemap/admin/components/Info/index.jsx
- packages/addons/sitemap/admin/tabs/Settings/index.jsx
Improve experience of sitemap plugin for first use.
The logic to determine which content to show when no sitemap was generated was outdated.
Install the sitemap addon to a new site and observe that the following is no longer present:
> fix: warning about uncontrolled to controlled input
